### ISSUE TITLE
Integration with RocksDB

### ISSUE THREAD

**Issue by ywang-wnlo** [dsrhaslab/paio#2]
Hi~
Integration with RocksDB code don't seem to be found in that repository,
Could you please provide the rocksdb version and patch file?

**Comment by rgmacedo** [comment]
To use PAIO in RocksDB, there are three main changes that need to be done: 
- **io_posix** ([src](https://github.com/facebook/rocksdb/blob/f438b98e552010613cff8684a7d84191ed785148/env/io_posix.cc) / [header)](https://github.com/facebook/rocksdb/blob/f438b98e552010613cff8684a7d84191ed785148/env/io_posix.h): added enforcement calls to rate limit specific POSIX operations submitted from RocksDB to the file system;
- **env** ([src](https://github.com/facebook/rocksdb/blob/f438b98e552010613cff8684a7d84191ed785148/env/env.cc) / [header](https://github.com/facebook/rocksdb/blob/f438b98e552010613cff8684a7d84191ed785148/include/rocksdb/env.h)): create stage and necessary structures to hold context propagation information;
- **[env_posix](https://github.com/facebook/rocksdb/blob/f438b98e552010613cff8684a7d84191ed785148/env/env_posix.cc)**, **[compaction-job](https://github.com/facebook/rocksdb/blob/f438b98e552010613cff8684a7d84191ed785148/db/compaction_job.cc)**, **[flush-job](https://github.com/facebook/rocksdb/blob/f438b98e552010613cff8684a7d84191ed785148/db/flush_job.cc)**, and **[threadpool-impl](https://github.com/facebook/rocksdb/blob/f438b98e552010613cff8684a7d84191ed785148/util/threadpool_imp.cc)**: instrumentation for the context propagation (identify which high-level operation will originate a given POSIX request).

**Note:** the RocksDB version used in the PAIO paper was [v5.17.2](https://github.com/facebook/rocksdb/tree/v5.17.2).
